AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AgilFacil

#------------  Parameters ------------#
Parameters:
  NameParameter:
    Type: String
    Default: " "

Resources:

  TableBoard: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "dateTime"
          AttributeType: "S"
        - AttributeName: "boardId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "boardId"
          KeyType: "HASH"
        - AttributeName: "dateTime"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: 'board'

      GlobalSecondaryIndexes: 
        - IndexName: "gsi_board_user"
          KeySchema: 
            - AttributeName: "userId"
              KeyType: "HASH"
            - AttributeName: "dateTime"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: INCLUDE
            NonKeyAttributes: 
              - boardId
              - boardName
              - userName
              - squadName
              - areaName