AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AgilFacil

#------------  Parameters ------------#
Parameters:
  NameParameter:
    Type: String
    Default: " "

Resources:

  TableBoard: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "date_time"
          AttributeType: "S"
        - AttributeName: "board_id"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "board_id"
          KeyType: "HASH"
        - AttributeName: "date_time"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: 'board'

      GlobalSecondaryIndexes: 
        - IndexName: "gsi_board_user"
          KeySchema: 
            - AttributeName: "user_id"
              KeyType: "HASH"
            - AttributeName: "date_time"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: INCLUDE
            NonKeyAttributes: 
              - board_id
              - board_name
              - user_name
              - squad_name
              - area_name