AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AgilFacil

#------------  Parameters ------------#
Parameters:
  ClientIDGoogle:
    Type: String
  ClientSecretGoogle:
    Type: String
  EmailVerificationSubject:     
    Type: String
    Default: "Confirmação de email - AgilFacil"
  EmailVerificationMessage:     
    Type: String
    Default: "Clique no link abaixo para verificar seu email: {####}"


Resources:

  TableBoard: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "creatorId"
          AttributeType: "S"
        - AttributeName: "dateTime"
          AttributeType: "S"
        - AttributeName: "boardId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "boardId"
          KeyType: "HASH"
        - AttributeName: "dateTime"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: 'board'

      GlobalSecondaryIndexes: 
        - IndexName: "gsi_board_user"
          KeySchema: 
            - AttributeName: "creatorId"
              KeyType: "HASH"
            - AttributeName: "dateTime"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: INCLUDE
            NonKeyAttributes: 
              - boardId
              - boardName
              - userName
              - squadName
              - areaName