AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  agilfacil.com.br

Globals:
  Function:
    Timeout: 10

#------------  Parameters ------------#
Parameters:
  UrlApiHealth:
    Type: String
    Default: "https://agilfacil.com.br:9000/healthcheck"

Resources:
  
  #------------ Topic SNS ------------#
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "AlertInstanceEC2"
      TopicName: "alert-agilfacil"

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: "marcelomgabriel@gmail.com"


  #------------ Lambda Function ------------#
  AgilfacilHealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "agilfacil-health"
      CodeUri:  ./FunctionHealth
      Handler: agilfacil-health.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopic
          URL_API_HEALTH: !Ref UrlApiHealth
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "sns:Publish"
              Resource: !Ref SNSTopic

#------------ Schedule Lambda ------------#
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "AgilfacilHealthSchedule"  # Nome da regra
      ScheduleExpression: 'rate(1 hour)'  # Executa a cada 1 hora
      #ScheduleExpression: 'rate(1 minute)'  # Executa a cada 1 minuto
      Targets:
        - Arn: !GetAtt AgilfacilHealthFunction.Arn
          Id: "TargetFunctionV1"

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AgilfacilHealthFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledRule.Arn            